### ISSUE TITLE
图片中文字缺失

### ISSUE THREAD

**Issue by tsingcoo** [intro-llm/intro-llm.github.io#14]
书本119页图5.1 
如下两处x'跟x不一致
“提示:x' = 不小心错过了公共汽车。我感到 [z]” 应改为 “提示:x' = **我**不小心错过了公共汽车。我感到 [z]”
“结果:x' =不小心错过了公共汽车。我感到 太不好了” 应改为 “结果:x' =**我**不小心错过了公共汽车。我感到 太不好了”

**Comment by qzhangFDU** [comment]
感谢，已修正
