### ISSUE TITLE
句子语病问题

### ISSUE THREAD

**Issue by tsingcoo** [intro-llm/intro-llm.github.io#21]
书本 19页 2.1.4 残差连接与层归一化 第8行
“此外，为了进一步使得每一层的输入输出范围稳定在一个合理的范围内，层归一化技术被进一步引入每个 Transformer 块的当中:”
该句中的两个“范围”重复，两个“进一步”重复，句尾的“的当”多余。
修改建议如下：
“此外，为了使得每一层的输入输出稳定在一个合理的范围内，层归一化技术被进一步引入每个 Transformer 块中:”

**Comment by qzhangFDU** [comment]
已修正，感谢
