### ISSUE TITLE
术语错误

### ISSUE THREAD

**Issue by SchweitzerGAO** [intro-llm/intro-llm.github.io#22]
76页“全分片数据并行”的英文应为“Fully Sharded Data Parallel”而非"Fully Shared Data Parallel"

**Comment by SchweitzerGAO** [comment]
以及下方“2022 年 3 年发布的 NVIDIA H100 SXM ”应为“2022 年 3 月发布的 NVIDIA H100 SXM ”

**Comment by SchweitzerGAO** [comment]
以及图4.12标题应为FFN结构张量并行示意图

**Comment by SchweitzerGAO** [comment]
107页倒数第2段PyThorch应为Pytorch

**Comment by qzhangFDU** [comment]
都已经修改，感谢
