### ISSUE TITLE
语句错误

### ISSUE THREAD

**Issue by Chaochao2020** [intro-llm/intro-llm.github.io#28]
你好, 在 p121 页有监督微调章节, 5.2 高效模型微调部分, 第一段的第二句话多了个"被"字. 
_"为了节省成本, 研究人员提出了多种参数高效(Parameter Efficient)的微调方法**被**, 旨在仅训练少量参数使模型适应到下游任务."_

**Comment by qzhangFDU** [comment]
已修改  感谢
