### ISSUE TITLE
书中的代码问题

### ISSUE THREAD

**Issue by zhoucz97** [intro-llm/intro-llm.github.io#29]
老师您好，请问书中的代码是否可标注URL来源？或者将各章节可执行代码放到GitHub上，感觉这样方便读者直接运行。

**Comment by qzhangFDU** [comment]
后面会准备一个Github

纸质出版的书上，不允许出现链接，就没有加

**Comment by zhoucz97** [comment]
感谢张老师的回复，老师辛苦了~
