### ISSUE TITLE
请问《大语言模型理论与实践》何时更新，当前的版本是6月19日？

### ISSUE THREAD

**Issue by franztao** [intro-llm/intro-llm.github.io#3]

**Comment by XuLongjia** [comment]
写的很好，期待张老师早日更新！

**Comment by qzhangFDU** [comment]
最近太忙了  第三章估计这周末写完更新

**Comment by franztao** [comment]
每周都有追跟老师您的更新内容，更新的内容能布置一些思考问题吗？

**Comment by qzhangFDU** [comment]
感谢。  后面看看能不能加一点，赶在9月份前把大体成稿，时间比较紧张

**Comment by franztao** [comment]
![img_v2_464d0a76-c942-423b-81d6-114dffec19dg](https://github.com/intro-llm/intro-llm.github.io/assets/6941820/7b056b48-d773-424a-9182-851d62e1c38c)
![img_v2_366afd90-1792-4268-9b3a-e716649a614g](https://github.com/intro-llm/intro-llm.github.io/assets/6941820/c2c1f330-2264-4c66-b35e-0e172c2b2c71)
学习中，看到一些勘误，我就直接贴出来，反馈给老师您了

**Comment by qzhangFDU** [comment]
感谢

 

 

Best,

 

Qi Zhang

 

Professor

School of Computer Science

Fudan University

 

From: ***@***.***> on behalf of Franz ***@***.***>
Reply-To: "intro-llm/intro-llm.github.io" ***@***.***>
Date: Wednesday, August 2, 2023 at 10:56 AM
To: "intro-llm/intro-llm.github.io" ***@***.***>
Cc: Qi Zhang ***@***.***>, State change ***@***.***>
Subject: Re: [intro-llm/intro-llm.github.io] 请问《大语言模型理论与实践》何时更新，当前的版本是6月19日？ (Issue #3)

 



学习中，看到一些勘误，我就直接贴出来，反馈给老师您了

**Comment by franztao** [comment]
写的很好，期待张老师早日更新！

**Comment by franztao** [comment]
![image](https://github.com/intro-llm/intro-llm.github.io/assets/6941820/7e5cd5dc-e77b-4790-97d7-d30aa3bcf747)
