### ISSUE TITLE
基于9月26日版本的一些错误

### ISSUE THREAD

**Issue by panzhiyi** [intro-llm/intro-llm.github.io#30]
1. 24页脚标，引用错误。
2. 33页RMSNorm归一化函数小节，缺少逗号，第一段“针对输入向量aRMSNorm函数计算公式如下：”应改为“第一段“针对输入向量a，RMSNorm函数计算公式如下：”。
3. 38页图2.6，带状注意力和膨胀注意力的上方图像重复，应修改带状注意力的图。

**Comment by panzhiyi** [comment]
4. 121页，公式5.2，x的粗体非粗体形式不对应。

**Comment by panzhiyi** [comment]
5. 125页，公式5.8，分数表示错误，\frac{1}{d_2}。

**Comment by panzhiyi** [comment]
6. 149页，（3）强化学习可以更好的解决多轮对话……，该段最后缺少句号。

**Comment by qzhangFDU** [comment]
感谢都修正了
