### ISSUE TITLE
阅读本书发现的一些错别字等问题

### ISSUE THREAD

**Issue by wouldyoulikeme** [intro-llm/intro-llm.github.io#5]
您好，16页2.2.2第一段三个 线性变换，其中Q的符号写成了K。

**Comment by 121786404** [comment]
96页,  FP32、FP16 和BP16 表示如图4.15所示  , BP16应改为BF16

**Comment by qzhangFDU** [comment]
感谢！ 这两个都修正了

**Comment by yinruiqing** [comment]
121页 5.2第三行 微调方法被 -> 微调方法
124页 5.2.2 第二行 Stable Diffusino -> Stable Diffusion

**Comment by qzhangFDU** [comment]
感谢，已修正
