### ISSUE TITLE
前言中的疑问

### ISSUE THREAD

**Issue by xuhu0115** [intro-llm/intro-llm.github.io#55]
“2018 年 Google 的研究团队开创性地提出了预训练语言模型 BERT[1]，该模型在诸多自然语言 处理任务中展现了卓越的性能。这激发了大量以预训练语言模型为基础的自然语言处理研究，也引领了自然语言处理领域的预训练范式的兴起。然而，尽管这一变革影响深远，但它并没有改变每个模型只能解决特定问题的基本模式。“

你好，我非常喜欢这本书，在看到前言这部分的时候有一个小疑问，“但它并没有改变每个模型只能解决特定问题的基本模式“这里的它是指什么？是否可以解释一下呢？

**Comment by qzhangFDU** [comment]
它 指代的的Bert

**Comment by xuhu0115** [comment]
> 它 指代的的Bert

BERT 这种架构不再需要为每个任务设计复杂的特征工程和模型架构，而是可以基于同一个预训练模型快速应用到不同领域。为什么说BERT并没有改变这种模式呢？如何理解？

**Comment by qzhangFDU** [comment]
每个模型只能解决特定问题
