### ISSUE TITLE
数学符号部分错误

### ISSUE THREAD

**Issue by TaoRuan** [intro-llm/intro-llm.github.io#59]
线性代数(第7页)存在印刷错误：

[U; V ] 矩阵A 与V 沿行向量拼接

应为：
[U; V ] 矩阵U 与V 沿行向量拼接

<img width="677" alt="Screenshot 2024-08-06 at 18 29 30" src="https://github.com/user-attachments/assets/4917a336-5b66-402e-8640-47eb2f40459a">

**Comment by qzhangFDU** [comment]
新版本已上传，感谢
