### ISSUE TITLE
书本公式

### ISSUE THREAD

**Issue by zzhang0179** [intro-llm/intro-llm.github.io#6]
P159 (6.20) 
这个公式均方差的被减数 少乘了一个项
<img width="729" alt="image" src="https://github.com/intro-llm/intro-llm.github.io/assets/72484291/36f09961-3360-4a91-8e53-62f0fee9d1a6">

**Comment by zzhang0179** [comment]
P151（6.31） 到 （6.32）的公式 从全局的梯度优化 到了 单步(s_t, a_t) 的优化感觉可以加一些说明
另外P151 （6.33）下方θ上标没标上
<img width="622" alt="image" src="https://github.com/intro-llm/intro-llm.github.io/assets/72484291/3a2733c3-15fe-4dd3-b4bf-dc9813399668">

**Comment by zzhang0179** [comment]
书本P46页
“全局内存是所有线程都可以访问，但是本地内存只能当前线程访问。NVIDIA H100
中全局内存有 80GB 空间，其访问速度虽然可以达到 3.35TB/s。”
这句话似乎还没有讲完

**Comment by qzhangFDU** [comment]
上述问题均已修正，感谢
