### ISSUE TITLE
第六章6.3.1和6.3.3的内容应该进行修改

### ISSUE THREAD

**Issue by Light7Rain** [intro-llm/intro-llm.github.io#62]
感谢复旦团队的开源工作，为入门大模型提供了很好的学习材料！但本书第六章中6.3.1和6.3.3两个章节大量抄袭《Easy RL：强化学习教程》（2022，王琦，杨毅远，江季，人民邮电出版社）中“近端策略优化”的部分，公式、图片没有任何改动，作为一本已经出版的商业书籍，这是侵权行为，而且有违学术规范。请酌情对内容进行修改。

**Comment by qzhangFDU** [comment]
非常感谢您对我们开源工作的关注以及提出的宝贵意见。对于您指出的第六章中 6.3.1 和 6.3.3 两个章节与《Easy RL：强化学习教程》存在相似内容的问题，我们高度重视。新版本已经上传。感谢
